sabzsocial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social.urls', namespace='social')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = 'social'

urlpatterns = [
    path('', views.profile, name='profile'),
    # path('login/', views.login,name="login"),
    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm), name="login"),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('logout/', views.log_out, name="logout"),

    path('register/', views.register, name="register"),
    path('user/edit', views.edit_user, name="edit_account"),
    path('ticket/', views.ticket, name="ticket"),

    path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name="password_change"),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url='/password-reset/complete'),
         name="password_reset_confirm"),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('posts/', views.post_list, name="post_list"),
    path('posts/post/<slug:tag_slug>/', views.post_list, name="post_list_by_tag"),
    path('posts/create_post/', views.create_post, name="create_post"),
    path('posts/detail/<pk>', views.post_detail, name="post_detail"),
    path('like_post/', views.like_post, name='like_post'),
    path('save-post/', views.save_post, name='save_post'),
    path('users/', views.user_list, name='user_list'),
    path('users/<username>/', views.user_detail, name='user_detail'),
    path('users/<username>/<rel>', views.contact, name='user_contact'),
    path('follow/', views.user_follow, name='user_follow'),
    path('posts/<post_id>/comment/', views.post_comment, name="post_comment"),
]

social/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=250, required=True, label="نام کاربری یا تلفن یا ایمیل",
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=250, required=True, label="رمز عبور",
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                               label='پسورد')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                label='تکرار پسورد')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'phone']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
                'phone': forms.TextInput(attrs={
                    'class': 'form-control',
            }),
        }
        labels = {
            'username': 'نام کاربری',
            'first_name': 'نام',
            'last_name': 'نام خانوادگی',
            'phone': 'شماره تماس',

        }


    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('پسورد ها مطابقت ندارند!')
        return cd['password2']

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if User.objects.filter(phone=phone).exists():
            raise forms.ValidationError("phone already exists!")
        return phone


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email',
                  'phone', 'date_of_birth', 'bio', 'photo', 'job']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'phone': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
            }),
            'date_of_birth': forms.DateInput(attrs={
                'class': 'form-control',
            }),
            'bio': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'photo': forms.FileInput(attrs={
                'class': 'form-control',
            }),
            'job': forms.TextInput(attrs={
                'class': 'form-control',
            }),
        }
        labels = {
            'username': 'نام کاربری',
            'first_name': 'نام',
            'last_name': 'نام خانوادگی',
            'email': 'ایمیل',
            'date_of_birth': 'تاریخ تولد',
            'phone': 'شماره تماس',
            'bio': 'بایو',
            'job': 'شغل',

        }

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if User.objects.exclude(id=self.instance.id).filter(phone=phone).exists():
            raise forms.ValidationError("phone already exists!")
        return phone

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.exclude(id=self.instance.id).filter(username=username).exists():
            raise forms.ValidationError("username already exists!")
        return username


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    message = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField()
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن عددی نیست!")
            else:
                return phone


class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول", widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label="تصویر دوم", widget=forms.FileInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Post
        fields = ['description', 'tags']


class CommentForm(forms.ModelForm):
    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError("نام کوتاه است")
            else:
                return name

    class Meta:
        model = Comment
        fields = ['name', 'body']


social/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from .forms import *
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from .models import Post, Contact, Image
from taggit.models import Tag
from django.db.models import Count
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages


# Create your views here.


def log_out(request):
    logout(request)
    return HttpResponse("شما خارج شدید.")


def profile(request):
    try:
        user = User.objects.prefetch_related('followers', 'following').get(id=request.user.id)
    except:
        return redirect('social:login')
    saved_posts = user.saved_posts.all()[:7]
    my_posts = user.user_posts.all()[:8]
    following = user.get_followings()
    followers = user.get_followers()
    conntext = {
        'saved_posts': saved_posts,
        'my_posts': my_posts,
        'user': user,
        'following': following,
        'followers': followers,
        'form': CommentForm()
    }
    return render(request, 'social/profile.html', conntext)


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def edit_user(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user, files=request.FILES)
        if user_form.is_valid():
            user_form.save()
        return redirect('social:profile')
    else:
        user_form = UserEditForm(instance=request.user)
    context = {
        'user_form': user_form
    }
    return render(request, 'registration/edit_user.html', context=context)


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            message = f"{cd['name']}\n{cd['email']}\n{cd['phone']}\n\n{cd['message']}"
            send_mail(cd['subject'], message, 'abbasimobin1383@gmail.com', ['mobin04dev@gmail.com'],
                      fail_silently=False)
            messages.success(request, 'پیام شما به پشتبانی ارسال شد')
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})


def post_list(request, tag_slug=None):
    posts = Post.objects.select_related('author').order_by('-total_likes')
    latest_users = User.objects.filter(is_active=True).order_by('-date_joined')[:4]
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = Post.objects.filter(tags__in=[tag])

    page = request.GET.get('page')
    paginator = Paginator(posts, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = []

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'social/list_ajax.html', {'posts': posts})
    context = {
        'posts': posts,
        'tag': tag,
        'latest_users': latest_users,
    }
    return render(request, "social/list.html", context)


@login_required
def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('social:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create-post.html', {'form': form})


def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_post = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_post = similar_post.annotate(same_tags=Count('tags')).order_by('-same_tags', '-created')[:4]
    context = {
        'post': post,
        'similar_post': similar_post,
        'form':CommentForm()
    }
    return render(request, "social/detail.html", context)


@login_required
@require_POST
def like_post(request):
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = get_object_or_404(Post, id=post_id)
        user = request.user

        if user in post.likes.all():
            post.likes.remove(user)
            liked = False
        else:
            post.likes.add(user)
            liked = True

        post_likes_count = post.likes.count()
        response_data = {
            'liked': liked,
            'likes_count': post_likes_count,
        }
    else:
        response_data = {'error': 'Invalid post_id'}

    return JsonResponse(response_data)


@login_required
@require_POST
def save_post(request):
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = Post.objects.get(id=post_id)
        user = request.user

        if user in post.saved_by.all():
            post.saved_by.remove(user)
            saved = False
        else:
            post.saved_by.add(user)
            saved = True

        return JsonResponse({'saved': saved})
    return JsonResponse({'error': 'Invalid request'})


@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    return render(request, 'user/user_list.html', {'users': users})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    return render(request, 'user/user_detail.html', {'user': user})


@login_required
@require_POST
def user_follow(request):
    user_id = request.POST.get('id')
    if user_id:
        try:
            user = User.objects.get(id=user_id)
            if request.user in user.followers.all():
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
                follow = False
            else:
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                follow = True
            following_count = user.following.count()
            followers_count = user.followers.count()

            return JsonResponse({'follow': follow, 'following_count': following_count,
                                 'followers_count': followers_count})
        except User.DoesNotExist:
            return JsonResponse({'error': 'User does not exist.'})

    return JsonResponse({'error': 'Invalid request.'})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.name = request.user.first_name
        comment.save()
    return redirect('social:profile')


def contact(request, username, rel):
    user = User.objects.get(username=username)
    if rel == 'following':
        users = user.get_followings()
    else:
        users = user.get_followers()
    return render(request, 'user/user_list.html', {'users': users})

social/templates/social/detail.html
<div class="post" data-post-id="{{ post.id }}">
    {{ post.description |linebreaks }}
    published at {{ post.created }} by {{ post.author }}
    <br>
    <br>
    <button class="like-button">
        {% if request.user in post.likes.all %}
            Unlike
        {% else %}
            Like
        {% endif %}
    </button>

    <span class="likes-count">{{ post.likes.count }}</span> Likes
</div>

<button class="save-post">
    {% if request.user in post.saved_by.all %}
            UnSave
        {% else %}
            Save
        {% endif %}
</button>

<br>
{% for tag in post.tags.all %}
    <a href="{% url 'social:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
    {% if not forloop.last %}, {% endif %}
{% endfor %}

<h2>Similar posts</h2>
{% for post in similar_post %}
    <p>
        <a href="{{ post.get_absolute_url }}">{{ post.description |truncatewords:10 }}</a>
    </p>
    {% empty %}
        There are no similar posts
{% endfor %}


{% with comments.count as cm_count%}
<h3> {{ cm_count }} دیدگاه </h3>
{% endwith %}

{% for cm in comments %}
    <h5>{{ cm.name }}</h5>
    <p>{{ cm.body |linebreaks}}</p>
    <hr>
{% empty %}
    <p>کامنتی وجود ندارد!</p>
{% endfor %}

<h3>ثبت دیدگاه</h3>
<form method="post" action="{% url 'social:post_comment' post.id %}" >
    {% csrf_token %}
    {{ form.as_div }}
  <div>
    <button type="submit">ثبت</button>
  </div>
</form>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script></script>
<script>
    $(document).ready(function() {
        $('.like-button').click(function() {
            var button = $(this);

               $.ajax({
                type: 'POST',
                url: '{% url 'social:like_post' %}',
                data: {'post_id': {{post.id}}, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function(data) {
                    if (data.liked){
                        button.text('UnLike');
                    }
                    else {
                        button.text('Like');
                    }
                    $('.likes-count').text(data.likes_count);
                },
            });
        });
    });

    $(document).ready(function() {
        $('.save-post').click(function() {
            var button = $(this);

               $.ajax({
                type: 'POST',
                url: '{% url 'social:save_post' %}',
                data: {'post_id': {{post.id}}, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function(data) {
                    if (data.saved){
                        button.text('UnSave');
                    }
                    else {
                        button.text('Save');
                    }
                },

                error: function(error) {
                    console.log('خطا در ارسال درخواست Ajax: ' + error);
                }
            });
        });
    });
</script>

social/templates/social/list.html
{% if tag %}
    <h1> posts tagged with {{ tag.name }}</h1>
{% endif %}

<div id="post-list">
    {% for post in posts %}
        <a href="{{ post.get_absolute_url }}">
            {{ post.description |truncatewords:20 |linebreaks }}
        </a>
    {#    <img src="{{ post.photo.first.image_file.url }}" alt="{{ post.photo.first.url }}">#}
        published at {{ post.created }} by {{ post.author }}
        <br>
        {% for tag in post.tags.all %}
            <a href="{% url 'social:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
        <br>
        <br>
        <hr>
    {% endfor %}
</div>

<button id="load-more">بارگزاری بیشتر</button>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script></script>
<script>
    $(document).ready(function(){
        var page = 2;

        $('#load-more').click(function(){
            $.ajax({
                type : 'GET',
                url : "{% if tag %}{% url 'social:post_list_by_tag' tag_slug %}{% else %}{% url 'social:post_list' %}{% endif %}" + "?page=" + page,
                dataType : 'html',
                success : function(data){
                    $('#post-list').append(data);
                    page += 1
                }
            });
        });
    });
</script>

social/templates/social/list_ajax.html
{% for post in posts %}
    <a href="{{ post.get_absolute_url }}">
        {{ post.description |truncatewords:20 |linebreaks }}
    </a>
    <img src="{{ post.photo.first.image_file.url }}" alt="{{ post.photo.first.url }}">
    published at {{ post.created }} by {{ post.author }}
    <br>
    {% for tag in post.tags.all %}
        <a href="{% url 'social:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
    <br>
    <br>
    <hr>
{% endfor %}

social/templates/social/profile.html
{% extends 'parent/base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %} profile {% endblock %}

{% block content %}

	<!-- ==============================================
	 News Feed Section
	 =============================================== -->
	<section class="profile-two">
		<div class="container-fluid">
			<div class="row">

				<div class="col-lg-3">
					<aside id="leftsidebar" class="sidebar">
						<ul class="list">
							<li>
								<div class="user-info">
									<div class="image">
										<a href="#">
                                            {% if user.photo %}
											<img src="{% thumbnail user.photo 500x500 crop="0,0" %}" class="img-responsive img-circle"
												alt="User">
                                            {% else %}
                                                <img src="{% static 'images/profile/Avatar.png' %}" class="img-responsive img-circle">
                                            {% endif %}
											<span class="online-status online"></span>
										</a>
									</div>
									<div class="detail">
										<h4>{{ user.get_full_name }}</h4>
										<small>{{user.username}}</small>
									</div>
									<div class="row">
										<div class="col-12">
											<a title="facebook" href="#" class=" waves-effect waves-block"><i
													class="fab fa-facebook"></i></a>
											<a title="twitter" href="#" class=" waves-effect waves-block"><i
													class="fab fa-twitter"></i></a>
											<a title="instagram" href="#" class=" waves-effect waves-block"><i
													class="fab fa-instagram"></i></a>
										</div>
									</div>
								</div>
							</li>
							<li>
								<small class="text-muted"><a href="photo_profile_two.html">{{ user.user_posts.count }} پست<em
											class="fa fa-angle-left pull-left"></em></a> </small><br />
								<small class="text-muted"><a href="{% url 'social:user_contact' user.username 'followers' %}">{{ user.followers.count }} دنبال کننده<em
											class="fa fa-angle-left pull-left"></em></a> </small><br />
								<small class="text-muted"><a href="{% url 'social:user_contact' user.username 'following' %}">{{ user.following.count }} نفر را دنبال می کند <em
											class="fa fa-angle-left pull-left"></em></a> </small>
								<hr>
								<small class="text-muted">درباره: </small>
								<p>{{ user.bio}}</p>
								<hr>
								<small class="text-muted">شغل : </small>
								<p>{{ user.job }} </p>
                                <hr>
								<small class="text-muted">تاریخ تولد : </small>
								<p>{{ user.date_of_birth|date:"Y/m/d"}} </p>
								<hr>
							</li>
						</ul>
					</aside>
				</div>
				<!--/ col-lg-3-->

				<div class="col-lg-6" style="background: #fff;">
					<!--/ row -->

					<div class="row">
                    {% for my_post in my_posts %}
						<div class="col-lg-6">
							<a href="#myModal-{{ my_post.id }}" data-toggle="modal">
								<div class="explorebox" style="background: linear-gradient( rgba(34,34,34,0.2), rgba(34,34,34,0.2)), url('{{my_post.images.first.image_file.url}}') no-repeat;
					  background-size: cover;
					  background-position: center center;
					  -webkit-background-size: cover;
					  -moz-background-size: cover;
					  -o-background-size: cover;">
									<div class="explore-top">
										<div class="explore-like"><i class="fa fa-heart"></i> <span>{{ my_post.total_likes }}</span></div>
										<div class="explore-circle pull-left"><span>{{ my_post.total_saves }}&nbsp;</span><i class="far fa-bookmark"></i></div>
									</div>
								</div>
							</a>
						</div>
                        {% with post_id=my_post.id %}
                        {% include 'partials/my-modal.html' %}
                        {% endwith %}
                    {% endfor %}
					</div>
					<!--/ row -->

				</div>
				<div class="col-lg-3">
                    <div class="trending-box">
						<div class="row">
							<div class="col-lg-12">
								<h4>اخرین فالوینگ ها</h4>
							</div>
						</div>
					</div>
					<div class="suggestion-box full-width">
						<div class="suggestions-list">
                            {% for flw in following|slice:"0:5" %}
							<div class="suggestion-body">
                            {% if flw.photo %}
								<img class="img-responsive img-circle" src="{{ flw.photo.url}}" alt="">
                            {% else %}
                                <img class="img-responsive img-circle" src="{% static 'images/profile/Avatar.png' %}" alt="">
                            {% endif %}
								<div class="name-box">
									<h4>{{ flw.get_full_name}}</h4>
									<span>{{flw.username}}</span>
								</div>
{#								<span><i class="fa fa-plus"></i></span>#}
							</div>
                            {% endfor %}
						</div>
						<!--suggestions-list end-->
					</div>

                      <div class="trending-box">
						<div class="row">
							<div class="col-lg-12">
								<h4>اخرین فالور ها</h4>
							</div>
						</div>
					</div>
					<div class="suggestion-box full-width">
						<div class="suggestions-list">
                            {% for follower in followers|slice:"0:5" %}
							<div class="suggestion-body">
                            {% if follower.photo %}
								<img class="img-responsive img-circle" src="{{ follower.photo.url}}" alt="">
                            {% else %}
                                <img class="img-responsive img-circle" src="{% static 'images/profile/Avatar.png' %}" alt="">
                            {% endif %}
								<div class="name-box">
									<h4>{{ follower.get_full_name}}</h4>
									<span>{{ follower.username }}</span>
								</div>
{#								<span><i class="fa fa-plus"></i></span>#}
							</div>
                            {% endfor %}
						</div>
						<!--suggestions-list end-->
					</div>

					<div class="trending-box">
						<div class="row">
							<div class="col-lg-12">
								<h4>پست‌های سیو شده شما</h4>
							</div>
						</div>
					</div>

					<div class="trending-box">
                        {% for post in saved_posts %}
						<div class="row">
                        	{% if forloop.counter0|divisibleby:2 %}
							<div class="col-lg-6">
								<a href="{{post.get_absolute_url}}"><img src="{{post.images.first.image_file.url}}" class="img-responsive" alt="Image" /></a>
							</div>
                            {% else %}
							<div class="col-lg-6">
								<a href="{{post.get_absolute_url}}"><img src="{{post.images.first.image_file.url}}" class="img-responsive" alt="Image" /></a>
							</div>
                        {% endif %}
						</div>
                        {% endfor %}

					</div>
			</div>

		</div>
        </div>
	</section>


	<!-- ==============================================
	 Scripts
	 =============================================== -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/base.js' %}"></script>
	<script src="{% static 'plugins/slimscroll/jquery.slimscroll.js' %}"></script>
	<script>
	$('#Slim,#Slim2').slimScroll({
	        height:"auto",
			position: 'right',
			railVisible: true,
			alwaysVisible: true,
			size:"8px",
		});
	</script>

{% endblock %}

social/templates/social/saved_posts.html
<h2>پست های سیو شده توسط شما</h2>
<ul>
    {% for post in saved_posts %}
        <a href="{{ post.get_absolute_url }}">
            {{ post.description |truncatewords:10 |linebreaks }}
        </a>
        published at {{ post.created }} by {{ post.author }}
        <br>
        <br>
        <hr>
    {% endfor %}
</ul>